file_path:
  qaqc_data_directory: .na
  noaa_directory: .na
  inflow_directory: .na
  configuration_directory: .na
  execute_directory: .na
  forecast_output_directory: .na
  run_config: .na
s3:
  drivers:
    endpoint: s3.flare-forecast.org
    bucket: drivers/noaa/gefs-v12-reprocess
  inflow_drivers:
    endpoint: s3.flare-forecast.org
    bucket: drivers/testing/inflow/parquet
  analysis:
    endpoint: s3.flare-forecast.org
    bucket: analysis/testing
  targets:
    endpoint: s3.flare-forecast.org
    bucket: targets/testing
  forecasts:
    endpoint: s3.flare-forecast.org
    bucket: forecasts/testing
  forecasts_parquet:
    endpoint: s3.flare-forecast.org
    bucket: forecasts/testing/parquet
  warm_start:
    endpoint: s3.flare-forecast.org
    bucket: restart/testing
  scores:
    endpoint: s3.flare-forecast.org
    bucket: scores/testing/parquet
location:
  site_id: fcre
  name: Falling Creek Reservoir
  latitude: 37.307
  longitude: -79.837
da_setup:
  da_method: enkf
  par_fit_method: perturb
  ensemble_size: 62
  localization_distance: 2
  no_negative_states: yes
  assimilate_first_step: no
  use_obs_constraint: TRUE
  inflation_factor: 1.1
model_settings:
  ncore: 4
  model_name: glm_aed
  base_GLM_nml: glm3.nml
  base_AED_nml: aed2.nml
  base_AED_phyto_pars_nml: aed_phyto_pars.csv
  base_AED_zoop_pars_nml: aed2_zoop_pars.nml
  modeled_depths:
  - 0.00
  - 0.25
  - 0.50
  - 0.75
  - 1.00
  - 1.25
  - 1.50
  - 1.75
  - 2.00
  - 2.25
  - 2.50
  - 2.75
  - 3.00
  - 3.25
  - 3.50
  - 3.75
  - 4.00
  - 4.25
  - 4.50
  - 4.75
  - 5.00
  - 5.25
  - 5.50
  - 5.75
  - 6.00
  - 6.25
  - 6.50
  - 6.75
  - 7.00
  - 7.25
  - 7.50
  - 7.75
  - 8.00
  - 8.25
  - 8.50
  - 8.75
  - 9.00
  - 9.25
  par_config_file: parameter_calibration_config_aed.csv
  obs_config_file: observations_config_aed.csv
  states_config_file: states_config_aed.csv
  depth_model_sd_config_file: depth_model_sd_aed.csv
default_init:
  lake_depth: 9.4
  temp:
  - 25.667
  - 24.9101
  - 23.067
  - 21.8815
  - 19.6658
  - 16.5739
  - 12.9292
  - 12.8456
  - 12.8127
  - 12.8079
  - 12.778
  temp_depths:
  - 0.127
  - 1.004
  - 2.005
  - 3.021
  - 4.002
  - 5.004
  - 6.004
  - 7.01
  - 8.001
  - 9.015
  - 9.518
  salinity: 0.0
  snow_thickness: 0.0
  white_ice_thickness: 0.0
  blue_ice_thickness: 0.0
inflow:
  use_forecasted_inflow: FALSE
met:
  use_forecasted_met: FALSE
uncertainty:
  observation: yes
  process: yes
  weather: yes
  initial_condition: yes
  parameter: yes
  met_downscale: yes
  inflow_process: yes
output_settings:
  diagnostics_names:
  - extc
  - PHY_green_fPho
  - PHY_green_fT
  - PHY_green_fNit
  - PHY_par
  - PHY_upt_dic
  - PHY_upt_po4
  - PHY_upt_n2
  - PHY_upt_nh4
  - PHY_upt_no3
  - PHY_green_gpp_c
  - PHY_green_rsp_c
  - PHY_green_exc_c
  - PHY_green_mor_c
  - PHY_green_set_c
