restart_file: .na
start_datetime: 2023-12-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2023-12-10 00:00:00
forecast_horizon: 5
sim_name: Simstrat
configure_flare: configure_flare_Simstrat.yml
configure_obs: observation_processing.yml
use_s3: FALSE
