restart_file: .na
start_datetime: 2023-12-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2020-11-08 00:00:00
forecast_horizon: 30
sim_name: GOTM
configure_flare: configure_flare_GOTM.yml
configure_obs: observation_processing.yml
use_s3: yes
