on:
  workflow_dispatch:
  schedule:
  - cron: "0 13 * * *"

jobs:
  build:
    runs-on: self-hosted
    container:
      image: rqthomas/flare-rocker:4.3.1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install deps
        shell: Rscript {0}
        run: |
          remotes::install_github('LTREB-reservoirs/ver4castHelpers')
          install.packages('rLakeAnalyzer')

# Point to the right path, run the right Rscript command
      - name: Run automatic prediction file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:  Rscript $GITHUB_WORKSPACE/workflows/glm_aed/combined_run_aed.R
